language: elixir

elixir:
  - 1.3.3

otp_release:
  - 18.1

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

script:
  - mix compile --warnings-as-errors
  - mix test
  - mix dogma
